<a href="https://colab.research.google.com/github/amann45/rough/blob/main/TitanicModels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [419]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [420]:
df = pd.read_excel('/content/76_batch3.xlsx')
df.head()

,Roll No.,Attendance,ADT I,ADT II,ADT III,Assignment,Lab,Total,results
0,76001,30,5,6,16,4,10,71,43.292683
1,76002,26,11,11,28,20,10,106,64.634146
2,76003,30,10,9,24,13,10,96,58.536585
3,76004,30,12,12,43,20,10,127,77.439024
4,76005,28,11,7,33,15,10,104,63.414634

In [421]:
df.columns

Index(['Roll No.', 'Attendance', 'ADT I', 'ADT II', 'ADT III', 'Assignment',
       'Lab', 'Total', 'results'],
      dtype='object')

In [422]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    91 non-null     int64
 1   Attendance  91 non-null     int64
 2   ADT I       91 non-null     int64
 3   ADT II      91 non-null     int64
 4   ADT III     91 non-null     int64
 5   Assignment  91 non-null     int64
 6   Lab         91 non-null     int64
 7   Total       91 non-null     int64
 8   results     91 non-null     float64
dtypes: float64(1), int64(8)
memory usage: 6.5 KB

In [423]:
df['results'] = df['Total'].apply(lambda x: 'Pass' if x >= 66 else 'Fail')

In [424]:
X = df[['Attendance', 'ADT I', 'ADT II', 'ADT III','Assignment', 'Lab','Total']]
y = df['results']

In [425]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll No.    91 non-null     int64
 1   Attendance  91 non-null     int64
 2   ADT I       91 non-null     int64
 3   ADT II      91 non-null     int64
 4   ADT III     91 non-null     int64
 5   Assignment  91 non-null     int64
 6   Lab         91 non-null     int64
 7   Total       91 non-null     int64
 8   results     91 non-null     object
dtypes: int64(8), object(1)
memory usage: 6.5+ KB

### LogisticRegression

In [426]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)
model= LogisticRegression()

In [427]:
model.fit(x_train,y_train) # feature scaling not needed for logistic regression

LogisticRegression()

In [428]:
y_test

40    Pass
22    Fail
55    Pass
88    Pass
0     Pass
26    Pass
39    Pass
66    Pass
10    Pass
44    Pass
85    Pass
35    Pass
70    Pass
62    Pass
12    Pass
4     Pass
18    Pass
28    Pass
49    Pass
Name: results, dtype: object

In [429]:
y_pred= model.predict(x_test)
y_pred

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass'], dtype=object)

In [430]:
print(df['results'].value_counts())

results
Pass    87
Fail     4
Name: count, dtype: int64

In [431]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [432]:
accuracy_score(y_test,y_pred)

1.0

In [433]:
confusion_matrix(y_test,y_pred)

array([[ 1,  0],
       [ 0, 18]])

In [434]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00        18

    accuracy                           1.00        19
   macro avg       1.00      1.00      1.00        19
weighted avg       1.00      1.00      1.00        19

### Naive Bayes

In [442]:
# feature scaling data is not needed for naive bayes
from sklearn.naive_bayes import GaussianNB

In [443]:
model_NB= GaussianNB()
model_NB.fit(x_train,y_train)

GaussianNB()

In [444]:
y_pred_NB= model_NB.predict(x_test)
y_pred_NB

array(['Pass', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass'], dtype='<U4')

In [445]:
accuracy_score(y_test,y_pred_NB)

0.9473684210526315

In [446]:
confusion_matrix(y_test,y_pred_NB)

array([[ 1,  0],
       [ 1, 17]])

In [447]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

        Fail       0.50      1.00      0.67         1
        Pass       1.00      0.94      0.97        18

    accuracy                           0.95        19
   macro avg       0.75      0.97      0.82        19
weighted avg       0.97      0.95      0.96        19

### Decision Tree

In [448]:
# feature scaling data is needed for decision tree
from sklearn.tree import DecisionTreeClassifier
model_DT= DecisionTreeClassifier(random_state=42)

In [449]:
model_DT.fit(x_train_scaled,y_train) # we used previously scaled data for decision tree

DecisionTreeClassifier(random_state=42)

In [450]:
y_pred_DT=model_DT.predict(x_test_scaled)
y_pred_DT

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass'], dtype=object)

In [451]:
accuracy_score(y_test,y_pred_DT)

1.0

In [452]:
confusion_matrix(y_test,y_pred_DT)

array([[ 1,  0],
       [ 0, 18]])

In [453]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00        18

    accuracy                           1.00        19
   macro avg       1.00      1.00      1.00        19
weighted avg       1.00      1.00      1.00        19

### Support Vector Machines (SVM)

In [454]:
# feature scaling data is needed for SVM
from sklearn.svm import SVC
model_SVM= SVC(kernel='rbf')

In [455]:
model_SVM.fit(x_train_scaled,y_train)

SVC()

In [456]:
y_pred_svm= model_SVM.predict(x_test_scaled)
y_pred_svm

array(['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass'], dtype=object)

In [457]:
accuracy_score(y_test,y_pred_svm)

0.9473684210526315

In [458]:
confusion_matrix(y_test,y_pred_svm)

array([[ 0,  1],
       [ 0, 18]])

In [459]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00         1
        Pass       0.95      1.00      0.97        18

    accuracy                           0.95        19
   macro avg       0.47      0.50      0.49        19
weighted avg       0.90      0.95      0.92        19

**Random Forest**

In [460]:
from sklearn.ensemble import RandomForestClassifier

In [461]:
rf_model = RandomForestClassifier(
    n_estimators=100,     # number of trees
    max_depth=None,       # let trees grow fully
    random_state=42,
)

In [462]:

rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [463]:
y_pred = rf_model.predict(x_test)

In [464]:
accuracy = accuracy_score(y_test, y_pred)

In [465]:
accuracy

1.0